M48
; DRILL file {KiCad (6.0.0)} date Mon Jan 24 17:50:57 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-24T17:50:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X115.062Y-60.96
X115.062Y-124.46
X233.68Y-60.96
X233.68Y-124.46
T0
M30
